### PR TITLE
MHub / GC - Minor cleanup gc_lunglobes

### LINKED ISSUE #69: MHub / GC - gc_lunglobes > 1 GPU crash
- The model is currently crashing when more than one GPU is available and this requires explicit GPU selection on machines with >1 GPUs installed on the host machine. This needs to be addressed, as all MHub models are expected to run with the `--gpus all` option.

_Originally posted by @LennyN95 in https://github.com/MHubAI/models/issues/42#issuecomment-1824579306_

### The issue
When running the MHub docker container with the lobe segmentation code from this repository with the `--gpus all` flags enabled and having 2 or more GPUs we run into the following error: 

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/app/models/gc_lunglobes/utils/LobeSegmentationRunner.py", line 50, in task
    handle = segment_lobe_init()
  File "/app/src/test.py", line 1830, in segment_lobe_init
    lobe_seg_instance = LobeSegmentationTSTestCOVID(settings)
  File "/app/src/test.py", line 1524, in __init__
    self.init()
  File "/app/src/test.py", line 700, in init
    self.logger.info("Let's use", torch.cuda.device_count(), "GPUs!")
Message: "Let's use"
Arguments: (2, 'GPUs!')
```

This error appears to be related to incorrect formatting of the logger.info call. Furthermore, if the logging line is removed we get the following error:

```
  File "/app/models/gc_lunglobes/utils/LobeSegmentationRunner.py", line 51, in task
    seg_result_np = segment_lobe(handle, img_np, meta_dict)
  File "/app/src/test.py", line 1861, in segment_lobe
    pred = handle.run(transformed_data_dict)
  File "/app/src/test.py", line 1572, in run
    scan_level_inf = self.model.scan_level_inference(pad_scan).cpu().squeeze(0)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DataParallel' object has no attribute 'scan_level_inference'
```

Upon inspecting the latter issue it appears that getting the multi-GPU feature to work properly isn't as simple as wrapping the model with `torch.nn.DataParallel` because the wrapped model uses custom methods (i.e. `scan_level_inference`) for inference, which are not picked up by the DataParallel mechanism of PyTorch.

### Suggested fix

As fixing the multi-GPU feature properly would be quite some work, the broken multi-GPU feature could be disabled entirely by removal of the following lines:

https://github.com/DIAGNijmegen/bodyct-pulmonary-lobe-segmentation/blob/5a64b70504d46c042c30851a69cec370f1202e67/test.py#L699-L702

### PR DESCRIPTION
**Pull request by silvandeleemput**
Closes #69 

This PR adds two minor cleanups to the gc_lunglobes model code:
* My e-mail address has been updated to my new one.
* The `default.yml` pipeline has been simplified by removing the unnecessary `nifticonverter` since now this is supported by default by the DSegConverter as well.

### CODE REVIEW

**Comment by LennyN95** [comment]
`dicomseg_json_path: /app/models/xie2020_lobe_segmentation/config/dseg.json`
We no longer need to use the JSON (actually, the file has been removed already); 
we've that changes implemented on the patch-models branch, waiting for final testing before we merge into main (soon).

**Comment by silvandeleemput** [comment]
I have merged the main branch (which includes the patch-models branch changes) into this branch to resolve the conflicts, this should be good to add now.

**Comment by silvandeleemput** [comment]
Fixed the commit version of the linked model repo at the latest main branch commit found on 2023/09/13

**Comment by silvandeleemput** [comment]
@LennyN95 @denbonte What is the current planned line of action for this PR? It appears the meta.json file needs to be updated to the latest JSON schema. I guess this will be something that you guys can do best since you created the mata.json file for this model.

**Comment by LennyN95** [comment]
Thx for your status request @silvandeleemput:

- `meta.json` will be updated by us for all already implemented models synchronously with our server's backend.
- Please make sure the PR branch is up-to-date with the main branch (currently 41 commits behind MHubAI:main).
- The model is currently crashing when more than one GPU is available and this requires explicit GPU selection on machines with >1 GPUs installed on the host machine. This needs to be addressed, as all MHub models are expected to run with the `--gpus all` option.

**Comment by silvandeleemput** [comment]
> Thx for your status request @silvandeleemput:
> 
> * `meta.json` will be updated by us for all already implemented models synchronously with our server's backend.
> * Please make sure the PR branch is up-to-date with the main branch (currently 41 commits behind MHubAI:main).

That's fine, notify me once you have updated the meta.json

> * The model is currently crashing when more than one GPU is available and this requires explicit GPU selection on machines with >1 GPUs installed on the host machine. This needs to be addressed, as all MHub models are expected to run with the `--gpus all` option.

I created an issue for this here: #69, please provide the error codes and I'll forward the issue to the repo owner so hopefully he can fix it in the repo. Otherwise, we can easily patch it.

**Comment by silvandeleemput** [comment]
> * `meta.json` will be updated by us for all already implemented models synchronously with our server's backend.
> * Please make sure the PR branch is up-to-date with the main branch (currently 41 commits behind MHubAI:main).
> * The model is currently crashing when more than one GPU is available and this requires explicit GPU selection on machines with >1 GPUs installed on the host machine. This needs to be addressed, as all MHub models are expected to run with the `--gpus all` option.

PR branch has been brought up-to-date and the > 1 GPU issue (#69) has been addressed by referring to the new release of the algorithm which includes a fix.

**Comment by LennyN95** [comment]
@silvandeleemput I checked the Metadata, and we need some minor information to merge this PR. 
- specify the dates for code and publication (all date formats need to be `yyyy-mm-dd`) 
- specify true/false under `summary.data.public`
- change `summary.model.training` to `supervised`

**Comment by silvandeleemput** [comment]
> @silvandeleemput I checked the Metadata, and we need some minor information to merge this PR.
> 
> * specify the dates for code and publication (all date formats need to be `yyyy-mm-dd`)
> * specify true/false under `summary.data.public`
> * change `summary.model.training` to `supervised`

It has been updated.

**Comment by LennyN95** [comment]
Thank you @Sil, looks like `false` must not be placed in quotes or is recognized as a string instead of a boolean.

**Comment by LennyN95** [comment]
When you're at it @Sil, can you also update the slice thickness (see https://github.com/MHubAI/coordination/issues/137)?

**Comment by silvandeleemput** [comment]
> Thank you @sil, looks like false must not be placed in quotes or is recognized as a string instead of a boolean.

Of course, fixed!

> When you're at it @sil, can you also update the slice thickness (see https://github.com/MHubAI/coordination/issues/137)?

The link for the mentioned issue seems to be broken. For now, I change the slice thickness to 0.75mm in line with the pixel spacing of the training data.

**Review by LennyN95 — APPROVED** [review]

**Comment by LennyN95** [comment]
> The link for the mentioned issue seems to be broken. For now, I change the slice thickness to 0.75mm in line with the pixel spacing of the training data.

Sorry, @silvandeleemput that is pointing to a private issue repo we used to keep track of things internally; I forgot it wasn't public. But changes are looking good, I'll merge and run the tests. Thanks!

**Comment by LennyN95** [comment]
@silvandeleemput the model didn't provide any output.

I checked what could've went wrong: you removed the NiftiConverter but specified `source_segs: nifti:mod=seg`. 
Solutions are to either remove that line (the default value for `DSegConverter.source_segs` contains mha, nifti and nrrd) or specify `mha` as the file type.

I'll fix this and run the build pipeline again. Please always test-run models after any implementational changes ;)

**Pull request merged**
