### PR TITLE
add segdb install to all base Dockerfiles

### PR DESCRIPTION
**Pull request by LennyN95**
Adding the new segdb python package to our base image Dockerfiles to prepare for the next mhubio update where we'll dismiss the old ymldicomseg utility and convert to using the more general and enhanced segdb package instead.

### CODE REVIEW

**Comment by LennyN95** [comment]
@denbonte rebuilding of image scan wait until the change is effective in mhubio.

**Comment by denbonte** [comment]
Perfect. Just let me know when (or run it through the automation scripts straight away if immediately needed!)

**Comment by LennyN95** [comment]
@denbonte changes in mhubio are already pushed with commit [66cf008d](https://github.com/MHubAI/mhubio/commit/66cf008d4e022d99355ab57666a9e86266545343).

So once I merge (I think you forgot to approve th ePR...), you can run the script to re-build the images.

**Comment by denbonte** [comment]
Gotcha - I'll do it in a moment! Feel free to merge without review if you want 🙂

**Pull request merged**
