### PR TITLE
Add Xie lobe segmentation algorithm as MHub model

### PR DESCRIPTION
**Pull request by silvandeleemput**
Hi, as discussed today, here is the code for the lobe segmentation algorithm integration. I forked the MHubAI/models repo and added the Xie lobe segmentation algorithm in a separate branch. I wanted to create a PR to a new similarly named branch in your repo, but I don't have permission to do that (create a new branch on your repo), so be aware that this PR will be aimed at the `main` branch. 

This PR should at least be a good starting point with access to the code, so you can pull the changes yourself in a different branch if you rather have that.

### CODE REVIEW

**Comment by denbonte** [comment]
Hey @silvandeleemput,

Thanks for the great work 🙃 

We accepted the PR and pushed some modifications to fix a couple of problems (so that it's also easy for you to compare the files via Github). I'll leave a couple of notes here below, describing what we modified and why - so that hopefully that can be helpful for the next contributions!

---

Note: we're not dead set on the name of the container/output and so on, so any input will be very welcome! What do you think about "Lung Lobes RTSU-Net" as the model name, and `rtsunet_lunglobes` as model tag (e.g., in dockerhub and so on)? (named after what's in the IEEE paper!)

FYI - for now, the CPU-only and CUDA-enabled containers are named `mhubai/xie2020_lobe_segmentation:nocuda` and `mhubai/xie2020_lobe_segmentation:cuda11.4`, respectively.

**Comment by denbonte** [comment]
## Useful Links

GC-MHub repo: https://github.com/DIAGNijmegen/MHubAI_models/tree/m-lobesegmentation-xie/models/xie2020_lobe_segmentation

MHub model branch: https://github.com/MHubAI/models/tree/m-lobesegmentation-xie

Original model repo: https://github.com/DIAGNijmegen/bodyct-pulmonary-lobe-segmentation

---

## Fixing the Export Problem

First of all, I cloned the `MHubAI_models` repo locally and checked-out to the model branch. I built the container running:

```
docker build -f xie2020_lobe_segmentation/dockerfiles/nocuda/Dockerfile . --no-cache --tag mhubai/xie2020_lobe_segmentation:nocuda
```

after `cd`'ing in `git/DIAGNijmegen-org/MHubAI_models/models`. The build is ok.

Upon first inspection:

```
docker run --volume=/home/dennis/Desktop/sample_data/input_dcm:/app/data/input_data --volume=/home/dennis/Desktop/sample_data/output_data:/app/data/output_data --gpus all mhubai/xie2020_lobe_segmentation:nocuda
```

The model works but doesn't output anything. By running the container in interactive mode:

```
docker run --volume=/home/dennis/Desktop/sample_data/input_dcm:/app/data/input_data --volume=/home/dennis/Desktop/sample_data/output_data:/app/data/output_data --gpus all -it --rm --entrypoint bash mhubai/xie2020_lobe_segmentation:nocuda
```

it is clear the segmentation data is being saved in the wrong folder (`/app/data/sorted/` instead of the mounted location `/app/data/output_data/`). The container also prints this during the run:

```
Writing image to /app/data/sorted/1.2.826.0.1.3680043.8.498.99748665631895691356693177610672446391/xie2020lobeseg.nrrd
```

This is due to [this line of code](https://github.com/DIAGNijmegen/MHubAI_models/blob/m-lobesegmentation-xie/models/xie2020_lobe_segmentation/utils/LobeSegmentationRunner.py#L86) in the Runner script (we don't want the output file to be saved where the input file is parsed from, which is `instance.abspath`; the problem can be solved simply by [specifying and creating an `out_dir` as we do in the PlatiPy case](https://github.com/MHubAI/models/blob/main/models/platipy/utils/PlatipyRunner.py#L24) or switch to the new paradigm based around decorators).

A simple example of the fix (no decorators):

```
[...]
        else:
            inp_data = instance.data.filter(DataType(FileType.NRRD, CT)).first()

        # define model output folder
        out_dir = self.config.data.requestTempDir(label="xie-model-out")

        # read image
        self.v(f"Reading image from {inp_data.abspath}")
[...]
```

```
[...]
        # store image
        out_file = os.path.join(out_dir, f'xie2020lobeseg.nrrd')
        self.v(f"Writing image to {out_file}")
        seg_itk = sitk.GetImageFromArray(seg_result_np)
        seg_itk.CopyInformation(img_itk)
        sitk.WriteImage(seg_itk, out_file)

        # meta
        meta = {
            "model": "Xie2020LobeSegmentation",
        }

        # create output data
        seg_data_type = DataType(FileType.NRRD, SEG + meta)           
        seg_data = InstanceData(out_file, type=seg_data_type)
        seg_data.dc.makeEntrypoint()
        seg_data.confirm()
        instance.addData(seg_data)
```

A better and more elegant fix (using decorators) [is available here](https://github.com/MHubAI/models/blob/m-lobesegmentation-xie/models/xie2020_lobe_segmentation/utils/LobeSegmentationRunner.py).

---

## Checking the Model Output

```
dennis@W2-S1:~/Desktop/sample_data/output_data$ python
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import SimpleITK as sitk
>>> img_sitk = sitk.ReadImage("xie2020lobeseg.nrrd")
>>> img = sitk.GetArrayFromImage(img_sitk)
>>> img.shape
(139, 512, 512)
>>> img.max()
5
>>> img.min()
0
```

After checking with 3DSlicer:

image


it looks like:
* segment_1 (int value 1) --> left lung, upper lobe
* segment_2 (int value 2) --> left lung, lower lobe
* segment_3 (int value 3) --> right lung, upper lobe
* segment_4 (int value 4) --> right lung, lower lobe
* segment_5 (int value 5) --> right lung, middle lobe

This also checks out by counting the frequency of the values in the mask (also printed by the runner):

```
>>> import numpy as np
>>> unique, counts = np.unique(img, return_counts=True)
>>> dict(zip(unique, counts))
{0: 32081626, 1: 1000263, 2: 1141280, 3: 992240, 4: 909103, 5: 313504}
```

---

## Adding the DICOM SEG Conversion

The NRRD file will be exported in the requested `tmp` directory and then copied by the organizer in the `output_data` folder. Still, the DICOM SEG conversion is not implemented at this point.

To fix that, we would need to add to the `run.py` file:

```
# convert (seg:nifti -> seg:dicomseg)
DsegConverter(config).execute()

[...]
organizer.setTarget(DataType(FileType.DICOMSEG, SEG), "/app/data/output_data/[i:SeriesID]/lunglobes_rtsunet.seg.dcm")
organizer.execute()
```

and add the module in the `config.yml` file:

```
DsegConverter:
    dicomseg_json_path: /app/models/xie2020_lobe_segmentation/config/dseg.json
    skip_empty_slices: True
```

Finally, for everything to work, we need to generate the DICOM SEG JSON manifesto. We can either use the [online DCMQI utility](http://qiicr.org/dcmqi/), or, even simpler, we could start from [that of a similar model in MHub](https://github.com/MHubAI/models/blob/main/models/lungmask/config/dseg.json):

```
{
  "ContentCreatorName": "MHub",
  "ClinicalTrialSeriesID": "0",
  "ClinicalTrialTimePointID": "1",
  "SeriesDescription": "Lung Lobes RTSU-Net",
  "SeriesNumber": "42",
  "InstanceNumber": "1",
  "BodyPartExamined": "Chest",
  "segmentAttributes": [
    [
      {
        "labelID": 1,
        "SegmentDescription": "Upper lobe of left lung",
        "SegmentAlgorithmType": "AUTOMATIC",
        "SegmentAlgorithmName": "Lung Lobes RTSU-Net",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeValue": "123037004",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Anatomical Structure"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeValue": "45653009",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Upper lobe of lung"
        },
        "SegmentedPropertyTypeModifierCodeSequence": {
          "CodeValue": "7771000",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Left"
        },
        "recommendedDisplayRGBValue": [
          42,
          183,
          144
        ]
      },
      {
        "labelID": 2,
        "SegmentDescription": "Lower lobe of left lung",
        "SegmentAlgorithmType": "AUTOMATIC",
        "SegmentAlgorithmName": "Lung Lobes RTSU-Net",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeValue": "123037004",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Anatomical Structure"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeValue": "90572001",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Lower lobe of lung"
        },
        "SegmentedPropertyTypeModifierCodeSequence": {
          "CodeValue": "7771000",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Left"
        },
        "recommendedDisplayRGBValue": [
          226,
          143,
          73
        ]
      },
      {
        "labelID": 3,
        "SegmentDescription": "Upper lobe of right lung",
        "SegmentAlgorithmType": "AUTOMATIC",
        "SegmentAlgorithmName": "Lung Lobes RTSU-Net",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeValue": "123037004",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Anatomical Structure"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeValue": "45653009",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Upper lobe of lung"
        },
        "SegmentedPropertyTypeModifierCodeSequence": {
          "CodeValue": "24028007",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Right"
        },
        "recommendedDisplayRGBValue": [
          73,
          155,
          228
        ]
      },
      {
        "labelID": 4,
        "SegmentDescription": "Lower lobe of right lung",
        "SegmentAlgorithmType": "AUTOMATIC",
        "SegmentAlgorithmName": "Lung Lobes RTSU-Net",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeValue": "123037004",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Anatomical Structure"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeValue": "90572001",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Lower lobe of lung"
        },
        "SegmentedPropertyTypeModifierCodeSequence": {
          "CodeValue": "24028007",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Right"
        },
        "recommendedDisplayRGBValue": [
          140,
          216,
          94
        ]
      },
      {
        "labelID": 5,
        "SegmentDescription": "Middle lobe of right lung",
        "SegmentAlgorithmType": "AUTOMATIC",
        "SegmentAlgorithmName": "Lung Lobes RTSU-Net",
        "SegmentedPropertyCategoryCodeSequence": {
          "CodeValue": "123037004",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Anatomical Structure"
        },
        "SegmentedPropertyTypeCodeSequence": {
          "CodeValue": "72481006",
          "CodingSchemeDesignator": "SCT",
          "CodeMeaning": "Middle lobe of right lung"
        },
        "recommendedDisplayRGBValue": [
          229,
          109,
          210
        ]
      }
    ]
  ],
  "ContentLabel": "SEGMENTATION",
  "ContentDescription": "Image segmentation",
  "ClinicalTrialCoordinatingCenterName": "dcmqi"
}
```

---

## Adding GPU support

The dockerfile we started working on does not support GPU (and it's based off the `mhubai/base:nocuda` image).

To enable GPU support, we need to build a second dockerfile with the following specifics:
* We need CUDA support in the base image; we can base the image off one of the MHub CUDA images (e.g., `mhubai/base:cuda11.4`)
* We need to install the proper libraries for the lobe segmentation model to work. This includes a GPU-enabled version of Torch (compatible with the highest number of GPUs possible) and a GPU-enabled version of DGL.

Let's start by basing the new dockerfile off `mhubai/base:cuda11.4`. After re-building the image with further changes, and confirming `nvidia-smi` and the NVIDIA support is working, we can spin the MHub container up:

```
docker run --volume=/home/dennis/Desktop/sample_data/input_dcm:/app/data/input_data --volume=/home/dennis/Desktop/sample_data/output_data:/app/data/output_data --gpus device=1 -it --rm --entrypoint bash mhubai/xie2020_lobe_segmentation:cuda11.4 
```

And test everything works with a GPU after installing the GPU-enabled versions of Torch and DGL:
```
pip install -f https://download.pytorch.org/whl/cu113/torch_stable.html \
               torch==1.10.0+cu113 \
               torchaudio==0.10.0+cu113 \
               torchvision==0.11.1+cu113
```

```
pip install dgl-cu113 -f https://data.dgl.ai/wheels/repo.html
```

--- 

After confirming everything works (N.B.: this could require a bit of back and forth, getting all of the versions of the packages right - especially when working with packages compiled for specific CUDA versions!), we can propagate the changes in the dockerfile.

We can then push all of the modifications described above first (leaving out modifications to the dockerfiles). Once the model folder is part of a branch of MHub, we can switch to `git sparse-checkout`, cloning from the `models` repository. We can test locally that everything works and, finally, commit and push the dockerfiles as well.

---

## Final Result

As a result of the process, running different models on the same piece of data is a matter of changing a few characters in the `docker run` command:

```
docker run \ 
	-v /home/dennis/Desktop/input_dcm:/app/data/input_data \
	-v /home/dennis/Desktop/:/app/data/output_data \
	--gpus device=1 mhubai/xie2020_lobe_segmentation:cuda11.4
```

```
docker run \ 
	-v /home/dennis/Desktop/input_dcm:/app/data/input_data \
	-v /home/dennis/Desktop/:/app/data/output_data \
	--gpus device=1 mhubai/totalsegmentator:cuda12.0
```

```
docker run \ 
	-v /home/dennis/Desktop/input_dcm:/app/data/input_data \
	-v /home/dennis/Desktop/:/app/data/output_data \
	--gpus device=1 mhubai/lungmask:cuda12.0
```

Furthermore, comparing models that carry out the same tasks (e.g., TotalSegmentator, LungMask, and the GC model) becomes way easier (as all the outputs are standardized!)

image

image

**Comment by silvandeleemput** [comment]
Thanks for the detailed rundown of the required changes. The added segmentation labels seem to be accurate. I also really like the decorators for the input/output mappings!

> Note: we're not dead set on the name of the container/output and so on, so any input will be very welcome! What do you think about "Lung Lobes RTSU-Net" as the model name, and `rtsunet_lunglobes` as model tag (e.g., in dockerhub and so on)? (named after what's in the IEEE paper!)

In principle, I would be fine with that name as it is more in line with the model tag naming conventions so far. However, I think the naming of the model tags will become increasingly important and one could argue that enforcing some kind of naming convention is actually desirable. For example, at some point, you might run into models/algorithms that use the same model and the same data type, say a new custom nn-UNet algorithm for the segmentation of the liver. You could name it `nnunet_liver_2`, but I think it is preferable that the model tag is named in such a way that it can easily distinguish between any two algorithms, hence I opted for the addition of the `xie2020` (model paper first author name + year of publication).  Ultimately if all models are properly indexed on the MHub webpage, the actual model tag might be less important, but it still might be something to consider.


Some more questions:
* I noticed that only the `cuda11.4` and not the `cuda12.0` was added. How important is it to have cuda12.0 enabled models?
* Do you have some updates regarding panimg support (https://github.com/DIAGNijmegen/rse-panimg) ?

**Comment by denbonte** [comment]
Hey Sil!

> I also really like the decorators for the input/output mappings!

@LennyN95 will be very happy to hear this 👀 

> In principle, I would be fine with that name as it is more in line with the model tag naming conventions so far. However, I think the naming of the model tags will become increasingly important and one could argue that enforcing some kind of naming convention is actually desirable. For example, at some point, you might run into models/algorithms that use the same model and the same data type, say a new custom nn-UNet algorithm for the segmentation of the liver. You could name it nnunet_liver_2, but I think it is preferable that the model tag is named in such a way that it can easily distinguish between any two algorithms, hence I opted for the addition of the xie2020 (model paper first author name + year of publication). Ultimately if all models are properly indexed on the MHub webpage, the actual model tag might be less important, but it still might be something to consider.

Thanks for the feedback!

> Some more questions:
> - I noticed that only the cuda11.4 and not the cuda12.0 was added. How important is it to have cuda12.0 enabled models?

I tried getting the model to work with `cuda12.0` but couldn't due to some dependencies-related issues. I suspect it might be just a matter of trying harder, but I did not want to push it and possibly break the model or have something else not working properly 🙃 

> - Do you have some updates regarding panimg support (https://github.com/DIAGNijmegen/rse-panimg) ?

We are looking forward to support `panimg` and work on MHA modules - we also already looked into converting back from MHA/processing MHAs for the standardisation procedures we have, and everything looks ok! 

We were "just" waiting to have a real necessity (e.g., if the other models you guys will provide will support other `sitk` formats, we might prioritize other open issues), but do let us know what's next on the collaboration roadmap and we'll be happy to plan accordingly!

**Pull request merged**
